<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/2
 * Time: 17:14
 */

namespace App\Http\Resources;


use Illuminate\Http\Resources\Json\Resource;

class ProductCategoryResponse extends Resource
{

	public function toArray($request)
	{
		return [
			'id'=>$this->id,
			'name'=>$this->name,
			'short_name'=>$this->short_name,
			'icon'=>$this->icon,
			'cover'=>$this->cover,
			'pid'=>$this->pid,
			'level'=>$this->level,
			'sort'=>$this->sort,
			'is_show'=>$this->is_show,
			'created_at'=>$this->created_at->format('Y-m-d'),
			'updated_at'=>$this->updated_at->timestamp,
		];
		//return parent::toArray($request); // TODO: Change the autogenerated stub
	}
}