<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/2
 * Time: 16:40
 */

namespace App\Http\Resources;


use Illuminate\Http\Resources\Json\Resource;

class SysRotateResponse extends Resource
{

	public function toArray($request)
	{
		return [
			'id'=>$this->id,
			'type'=>$this->type,
			'name'=>$this->name,
			'cover'=>$this->cover,
			'url'=>$this->url,
			'content'=>$this->content,
			'sort'=>$this->sort,
			'remark'=>$this->remark
		];
		return parent::toArray($request); // TODO: Change the autogenerated stub
	}
}