<?php

namespace App\Models;

use App\Scopes\StatusScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class AuthMember extends Authenticatable
{

    public $table = 'sys_members';

    protected static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
		static::addGlobalScope(new StatusScope());
	}
}
